<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo L('LOGIN_TITLE') . TITLE_SEPARATOR . L('BACKEND,MANAGE_CENTER') . TITLE_SEPARATOR . sys_config('sys_base_web_title'); ?></title>
    <?php echo $css_file, $js_file; ?>
    <script>
        var LOGIN_PAGE = true;
    </script>
</head>
<body>
</body>
</html>
