{template 'include', 'header'}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="panel">
            <div class="panel-header"><span class="icon-home"></span> 您现在的位置：<a href="#">首页</a>{BREAD_SEPARATOR}联系</div>
            <div class="panel-body">
                <address>
                    <strong>地址</strong>：深圳市南山区<br />
                    <strong>邮箱</strong>：first.last(at)example.com
                </address>
                <!--end 网文-->
            </div>
        </div><!--end span9-->
    </div><!--end row-fluid-->
</div><!--end container-fluid-->

{template 'include', 'footer'}