{template 'include', 'header'}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="panel">
            <div class="panel-header"><span class="icon-home"></span> 您现在的位置：<a href="#">首页</a>{BREAD_SEPARATOR}关于</div>
            <div class="panel-body">
                本站主要基于<a href="#">yaf</a>框架、<a href="#">thinkphp</a>核心开发。前台采用<a href="#">bootstrap</a>，后台采用<a href="#">Extjs 4.1.1a</a>。
                <!--end 网文-->
            </div>
        </div><!--end span9-->
    </div><!--end row-fluid-->
</div><!--end container-fluid-->

{template 'include', 'footer'}