<?php
//后台自动生成，请毋修改
//最后更新时间:2013-06-06 08:13:52

return array (
  'module_admin_verifycode_enable' => '1',
  'module_admin_verifycode_width' => '40',
  'module_admin_verifycode_height' => '20',
  'module_admin_verifycode_length' => '5',
  'module_admin_verifycode_type' => '5',
  'module_admin_verifycode_case' => '1',
  'module_admin_verifycode_order' => '4312',
  'module_admin_verifycode_refresh_limit' => '',
  'module_admin_verifycode_error_limit' => '',
  'module_guestbook_check' => '-1',
  'module_comments_check' => '-1',
  'module_guestbook_max_reply_level' => '-1',
  'module_comments_max_reply_level' => '-1',
  'module_guestbook_verifycode_error_limit' => '',
  'module_guestbook_verifycode_refresh_limit' => '',
  'module_guestbook_verifycode_order' => '4312',
  'module_guestbook_verifycode_case' => '1',
  'module_guestbook_verifycode_type' => '5',
  'module_guestbook_verifycode_length' => '5',
  'module_guestbook_verifycode_height' => '20',
  'module_guestbook_verifycode_width' => '40',
  'module_guestbook_verifycode_enable' => '0',
  'module_comments_verifycode_error_limit' => '',
  'module_comments_verifycode_refresh_limit' => '',
  'module_comments_verifycode_order' => '4312',
  'module_comments_verifycode_case' => '1',
  'module_comments_verifycode_type' => '5',
  'module_comments_verifycode_length' => '5',
  'module_comments_verifycode_height' => '20',
  'module_comments_verifycode_width' => '40',
  'module_comments_verifycode_enable' => '0',
  'module_guestbook_comments_check' => '0',
  'module_guestbook_comments_max_reply_level' => '5',
  'module_comments_alternation' => '-1',
  'module_guestbook_alternation' => '-1',
  'module_guestbook_comments_alternation' => '0',
  'module_guestbook_comments_disabled_username' => 'admin
yablog
mrmsl',
  'module_guestbook_disabled_username' => '',
  'module_guestbook_comments_disabled_ip' => '',
  'module_guestbook_disabled_ip' => '',
  'module_comments_disabled_ip' => '',
  'module_guestbook_comments_reply_admin_username' => 'admin',
  'module_guestbook_comments_reply_admin_email' => 'msl-138@163.com',
  'module_guestbook_comments_reply_admin_img' => '@common_imgcache@images/admin.png',
);