<?php
//后台自动生成，请毋修改
//最后更新时间:2013-06-06 08:29:06

return array (
  'sys_base_domain' => 'www.yablog.cn',
  'sys_base_http_protocol' => 'http',
  'sys_base_wwwroot' => 'v.2/',
  'sys_base_admin_entry' => 'yabadmin.php',
  'sys_base_web_name' => 'yablog',
  'sys_base_web_title' => 'yablog,又一个博客',
  'sys_base_web_index_title' => '首页',
  'sys_base_js_path' => 'static/js/',
  'sys_base_css_path' => 'static/css/',
  'sys_seo_keyword' => 'mrmsl',
  'sys_base_common_imgcache' => 'http://imgcache.yablog.cn/common/',
  'sys_base_admin_imgcache' => 'http://imgcache.yablog.cn/v.2/admin/',
  'sys_base_js_url' => 'http://imgcache.yablog.cn/v.2/yablog/js/',
  'sys_base_css_url' => 'http://imgcache.yablog.cn/v.2/yablog/css/',
  'sys_base_img_url' => 'http://imgcache.yablog.cn/v.2/yablog/images/',
  'sys_seo_description' => 'seo描述',
  'sys_base_closed' => '1',
  'sys_base_closed_reason' => '<div style="color: red">网站关闭了</div>',
  'sys_timezone_timediff' => '28800',
  'sys_timezone_default_timezone' => 'asia/shanghai',
  'sys_timezone_datetime_format' => 'Y-m-d H:i:s',
  'sys_timezone_date_format' => 'Y-m-d',
  'sys_timezone_time_format' => 'H:i:s',
  'sys_log_filesize' => '1024',
  'sys_log_level' => 'E_APP_SQL,E_APP_ROLLBACK_SQL',
  'sys_session_prefix' => 'mrmsl',
  'sys_session_name' => 'PHPSESSID',
  'sys_log_slowquery' => '2',
  'sys_session_save_handler' => 'files',
  'sys_session_gc_maxlifetime' => '1800',
  'sys_session_save_path' => '/',
  'sys_session_use_trans_id' => '0',
  'sys_session_use_cookies' => '1',
  'sys_session_use_only_cookies' => '1',
  'sys_session_cookie_secure' => '0',
  'sys_session_cookie_httponly' => '0',
  'sys_session_cookie_domain' => '@domain',
  'sys_session_cookie_lifetime' => '0',
  'sys_session_cookie_path' => '/',
  'sys_cookie_domain' => '@domain',
  'sys_cookie_path' => '/',
  'sys_cookie_expire' => '0',
  'sys_cookie_prefix' => 'mrmsl',
  'sys_log_systemerror' => '1',
  'sys_log_sqlerror' => '1',
  'sys_log_rollback_sql' => '1',
  'sys_template_admin_style' => '',
  'sys_memcache_host' => '127.0.0.1',
  'sys_memcache_port' => '11211',
  'sys_sphinx_host' => '127.0.0.1',
  'sys_sphinx_port' => '3312',
  'sys_verifycode_enable' => '1',
  'sys_verifycode_width' => '40',
  'sys_verifycode_height' => '20',
  'sys_verifycode_length' => '4',
  'sys_verifycode_order' => '0',
  'sys_verifycode_refresh_limit' => '5/10',
  'sys_verifycode_error_limit' => '5/10',
  'sys_verifycode_case' => '',
  'sys_verifycode_type' => '5',
  'sys_show_title_separator' => '-',
  'sys_show_bread_separator' => '&raquo;',
  'sys_base_copyright' => 'Copyright &copy; 2013 yablog 版权所有',
  'sys_mail_method' => 'smtp',
  'sys_mail_smtp' => 'smtp.163.com',
  'sys_mail_smtp_port' => '25',
  'sys_mail_email' => 'yablog@163.com',
  'sys_mail_password' => 'mrmsl170066918',
  'sys_mail_from_email' => 'mrmsl@qq.com',
  'sys_mail_from_name' => 'mrmsl',
  'sys_base_domain_scope' => '.yablog.cn',
  'sys_base_website' => 'http://www.yablog.cn/',
);