{template 'include', 'header'}

<div class="container-fluid">
    <div class="row-fluid panel">
            <div class="panel-header">
                <span class="icon-home"></span>
                {L NOW_POSITION}：<a href="{BASE_SITE_URL}">{L HOME}</a>
                {BREAD_SEPARATOR}
                {if isset($bread)}
                {$bread}
                {else}
                {L SYSTEM_INFOMATION}
                {/if}
            </div>
            <div class="panel-body text-center">
                {if isset($page_not_found)}
                <!--#include virtual="/{VERSION_PATH}ssi/404.shtml"-->
                {else}
                <img src="{COMMON_IMGCACHE}images/ok.gif" alt="" />
                {if isset($msg_content)}
                {$msg_content}
                {else}
                {L MESSAGE_CONTENT}
                {/if}
                {/if}
            </div>
    </div><!--end row-fluid-->
</div><!--end container-fluid-->

{template 'include', 'footer'}