<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo L('BACKEND,MANAGE_CENTER') . TITLE_SEPARATOR . sys_config('sys_base_web_title'); ?></title>
    <?php echo $css_file, $js_file; ?>
    <script>
        var ADMIN_ID = <?php echo ADMIN_ID; ?>;
        var ADMIN_ROLE_ID = <?php echo ADMIN_ROLE_ID; ?>;
        <?php
            echo "
            var ADMIN_INFO = {
                id: {$admin_info['admin_id']},
                username: '" . addslashes($admin_info['username']) . "',
                realname: '" . addslashes($admin_info['realname']) . "',
                lastLoginTime: '" . date(sys_config('sys_timezone_datetime_format'), $admin_info['last_login_time']) . "',
                lastLoginIp: '{$admin_info['last_login_ip']}',
                roleId: {$admin_info['role_id']},
                priv: " . ($admin_priv ? $admin_priv : '[]') . "
            };";
        ?>
    </script>
</head>
<body>
    <div id="layout" style="width: 99.2%; margin: 0 auto;">
        <div id="left" position="left"  title="主要菜单">
            <div>
                <ul id="tree" style="margin-top:3px;">
                    <li></li>
                </ul>
                </div>
        </div>
        <div position="center" id="tabs">
            <div title="管理中心" tabid="index">
                管理中心
            </div>
        </div>
    </div>
    <div id="div-header-content" class="x-hide-display">
        <span><?php echo L('HELLO'), ',', $admin_info['realname'], ' [', $role_info['role_name'], ']'; ?> | <a href="<?php echo BASE_SITE_URL; ?>" target="_blank"><?php echo L('WEBSITE,HOME'); ?></a> | <a href="<?php echo WEB_ADMIN_ENTRY; ?>/login/logout">退出</a> </span>
        <strong><?php echo L('BACKEND,MANAGE_CENTER'); ?></strong>
    </div>
</body>
</html>
