{template 'include', 'header'}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span9 panel">
            <div class="panel-header">
                <span class="icon-home"></span>
                {L NOW_POSITION}：<a href="{BASE_SITE_URL}">{L HOME}</a>
                {BREAD_SEPARATOR}
                {L GUESTBOOK}
            </div>
            <div class="panel-body">
                {$guestbook_html}
                {$paging}
                <div class="separation-add-comment">{L CN_FABIAO,GUESTBOOK}</div>
                <div id="form-panel"></div>
            </div>

        </div><!--end span9-->
        <div class="span3">
            <!--#include virtual="/{VERSION_PATH}ssi/hot_blogs.shtml"-->
            <!--#include virtual="/{VERSION_PATH}ssi/tags.shtml"-->
            <!--#include virtual="/{VERSION_PATH}ssi/new_comments.shtml"-->
        </div><!--end  span3-->
    </div><!--end row-fluid-->
</div><!--end container-fluid-->

{template 'include', 'footer'}