{template 'include', 'header'}
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span9 panel">
            <div class="panel-header"><span class="icon-home"></span> 您现在的位置：<a href="#">首页</a>{BREAD_SEPARATOR}留言</div>
            <div class="panel-body">
                <!--start 网文-->
                <div class="panel-list">
                    <h3><a href="/{VERSION_PATH}yabindex.php/blog/detail">文章标题</a></h3>
                    <p>内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</p>
                    <p>内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息...<a href="#">全文</a></p>
                    <p class="text-right muted">
                        <span class="actions">
                            <span class="icon-time icon-gray"></span>2013-02-21 11:32:502013-02-21 11:32:50
                            <span class="icon-zoom-in icon-gray ml-10"></span>
                            <a href="#" class="muted">
                                <span class="icon-thumbs-up icon-gray"></span>
                                <span class="counter">0</span>
                            </a>
                            <a href="#" class="muted"><span class="icon-comment icon-gray"></span><span class="counter">0</span></a>
                        </span>
                        <span class="pull-left"><span class="icon-tags icon-gray"></span> 标签：<a href="#">php</a>,<a href="#">js</a>,<a href="#">jquery</a></span>
                    </p>
                </div>
                <div class="panel-list">
                    <h3><a href="#">文章标题</a></h3>
                    <p>内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</p>
                    <p>内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息...<a href="#">全文</a></p>
                    <p class="text-right muted">
                        <span class="actions">
                            <span class="icon-time icon-gray"></span>2013-02-21 11:32:50
                            <span class="icon-zoom-in icon-gray ml-10"></span>10
                            <a href="#" class="muted">
                                <span class="icon-thumbs-up icon-gray"></span>
                                <span class="counter">0</span>
                            </a>
                            <a href="#" class="muted"><span class="icon-comment icon-gray"></span><span class="counter">0</span></a>
                        </span>
                        <span class="pull-left"><span class="icon-tags icon-gray"></span> 标签：<a href="#">php</a>,<a href="#">js</a>,<a href="#">jquery</a></span>
                    </p>
                </div>
                <div class="panel-list">
                    <h3><a href="#">文章标题</a></h3>
                    <p>内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</p>
                    <p>内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息...<a href="#">全文</a></p>
                    <p class="text-right muted">
                        <span class="actions">
                            <span class="icon-time icon-gray"></span>2013-02-21 11:32:50
                            <span class="icon-zoom-in icon-gray ml-10"></span>10
                            <a href="#" class="muted">
                                <span class="icon-thumbs-up icon-gray"></span>
                                <span class="counter">0</span>
                            </a>
                            <a href="#" class="muted"><span class="icon-comment icon-gray"></span><span class="counter">0</span></a>
                        </span>
                        <span class="pull-left"><span class="icon-tags icon-gray"></span> 标签：<a href="#">php</a>,<a href="#">js</a>,<a href="#">jquery</a></span>
                    </p>
                </div>
                <div class="pagination pagination-right">
                    <ul>
                        <li class="disabled"><span>首页</span></li>
                        <li class="disabled"><span>上一页</span></li>
                        <li class="active"><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">下一页</a></li>
                        <li><a href="#">尾页</a></li>
                    </ul>
                </div>
                <!--end 网文-->
            </div>
        </div><!--end span9-->
        <div class="span3">
            <div class="panel">
                <div class="panel-header"><h3>热门网文</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                    </ul>
                </div>
            </div>
            <div class="panel">
                <div class="panel-header"><h3>网文标签</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><a href="#">php</a></li>
                        <li><a href="#">javascript</a></li>
                        <li><a href="#">nodejs</a></li>
                        <li><a href="#">mongodb</a></li>
                        <li><a href="#">php</a></li>
                        <li><a href="#">javascript</a></li>
                        <li><a href="#">nodejs</a></li>
                        <li><a href="#">mongodb</a></li>
                    </ul>
                </div>
            </div>
            <div class="panel">
                <div class="panel-header"><h3>最新留言</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                    </ul>
                </div>
            </div>
        </div><!--end  span3-->
    </div><!--end row-fluid-->
</div><!--end container-fluid-->

{template 'include', 'footer'}