<div class="panel-list media panel-miniblog">
    <img class="media-object pull-left avatar" alt="图像" src="{COMMON_IMGCACHE}images/guest.png" />
    <div class="media-body">
        <div class="popover right">
            <div class="arrow"></div>
            <div class="popover-content">
                <span class="muted">2013-02-15 13:27:03</span>
                <a href="miniblog-detail.php">微博详情</a>
                <p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.</p>
                <p class="text-right actions"><a href="#" class="muted"><span class="icon-share-alt icon-gray"></span>回复</a></p>
                <div class="panel-list media panel-miniblog">
                    <img class="media-object pull-left avatar" alt="图像" src="{COMMON_IMGCACHE}images/guest.png" />
                    <div class="media-body">
                        <div class="popover right">
                            <div class="arrow"></div>
                            <div class="popover-content">
                                <span class="muted">2013-02-15 13:27:03</span>
                                <a href="miniblog-detail.php">微博详情</a>
                                <p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.</p>
                                <p class="text-right actions"><a href="#" class="muted"><span class="icon-share-alt icon-gray"></span>回复</a></p>
                                <div class="panel-list media panel-miniblog">
                                    <img class="media-object pull-left avatar" alt="图像" src="{COMMON_IMGCACHE}images/guest.png" />
                                    <div class="media-body">
                                        <div class="popover right">
                                            <div class="arrow"></div>
                                            <div class="popover-content">
                                                <span class="muted">2013-02-15 13:27:03</span>
                                                <a href="miniblog-detail.php">微博详情</a>
                                                <p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.</p>
                                                <p class="text-right actions"><a href="#" class="muted"><span class="icon-share-alt icon-gray"></span>回复</a></p>
                                                <div class="panel-list media panel-miniblog">
                                                <img class="media-object pull-left avatar" alt="图像" src="{COMMON_IMGCACHE}images/guest.png" />
                                                <div class="media-body">
                                                    <div class="popover right">
                                                        <div class="arrow"></div>
                                                        <div class="popover-content">
                                                            <span class="muted">2013-02-15 13:27:03</span>
                                                            <a href="miniblog-detail.php">微博详情</a>
                                                            <p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.</p>
                                                            <p class="text-right actions"><a href="#" class="muted"><span class="icon-share-alt icon-gray"></span>回复</a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="panel-list media panel-miniblog">
    <img class="media-object pull-left avatar" alt="图像" src="{COMMON_IMGCACHE}images/guest.png" />
    <div class="media-body">
        <div class="popover right">
            <div class="arrow"></div>
            <div class="popover-content">
                <span class="muted">2013-02-15 13:27:03</span>
                <a href="miniblog-detail.php">微博详情</a>
                <p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.</p>
                <p class="text-right actions"><a href="#" class="muted"><span class="icon-share-alt icon-gray"></span>回复</a></p>
                <div class="panel-list media panel-miniblog">
                    <img class="media-object pull-left avatar" alt="图像" src="{COMMON_IMGCACHE}images/guest.png" />
                    <div class="media-body">
                        <div class="popover right">
                            <div class="arrow"></div>
                            <div class="popover-content">
                                <span class="muted">2013-02-15 13:27:03</span>
                                <a href="miniblog-detail.php">微博详情</a>
                                <p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.</p>
                                <p class="text-right actions"><a href="#" class="muted"><span class="icon-share-alt icon-gray"></span>回复</a></p>
                                <div class="panel-list media panel-miniblog">
                                    <img class="media-object pull-left avatar" alt="图像" src="{COMMON_IMGCACHE}images/guest.png" />
                                    <div class="media-body">
                                        <div class="popover right">
                                            <div class="arrow"></div>
                                            <div class="popover-content">
                                                <span class="muted">2013-02-15 13:27:03</span>
                                                <a href="miniblog-detail.php">微博详情</a>
                                                <p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.</p>
                                                <p class="text-right actions"><a href="#" class="muted"><span class="icon-share-alt icon-gray"></span>回复</a></p>
                                                <div class="panel-list media panel-miniblog">
                                                <img class="media-object pull-left avatar" alt="图像" src="{COMMON_IMGCACHE}images/guest.png" />
                                                <div class="media-body">
                                                    <div class="popover right">
                                                        <div class="arrow"></div>
                                                        <div class="popover-content">
                                                            <span class="muted">2013-02-15 13:27:03</span>
                                                            <a href="miniblog-detail.php">微博详情</a>
                                                            <p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.</p>
                                                            <div class="popover bottom">
                                                                <div class="arrow"></div>
                                                                <div class="popover-title">回复留言</div>
                                                                <div class="popover-content">
                                                                    <form class="form-horizontal form-comment">
                                                                        <div class="control-group">
                                                                            <label class="control-label"><span class="text-error">*</span>用户名</label>
                                                                            <div class="controls">
                                                                                <input type="text" required />
                                                                            </div>
                                                                        </div>
                                                                        <div class="control-group">
                                                                            <label class="control-label"><span class="text-error">*</span>内容</label>
                                                                            <div class="controls">
                                                                                <textarea rows="3" cols="50" class="input-block-level" required></textarea>
                                                                            </div>
                                                                        </div>
                                                                        <div class="controls text-right">
                                                                            <button class="btn btn-primary">回复</button>
                                                                            <button class="btn">取消</button>
                                                                        </div>
                                                                    </form>
                                                                </div>
                                                            </div>
                                                            <p class="text-right actions"><a href="#" class="muted"><span class="icon-share-alt icon-gray"></span>回复</a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="pagination pagination-right">
    <ul>
        <li class="disabled"><span>首页</span></li>
        <li class="disabled"><span>上一页</span></li>
        <li class="active"><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">下一页</a></li>
        <li><a href="#">尾页</a></li>
    </ul>
</div>

<div class="separation-add-comment">发表留言</div>
<form class="form-horizontal form-comment">
    <div class="control-group">
        <label class="control-label"><span class="text-error">*</span>用户名</label>
        <div class="controls">
            <input type="text" required />
        </div>
    </div>
    <div class="control-group">
        <label class="control-label"><span class="text-error">*</span>内容</label>
        <div class="controls">
            <textarea rows="3" cols="50" class="input-block-level" required></textarea>
        </div>
    </div>
    <div class="controls text-right">
        <button class="btn btn-primary">回复</button>
        <button class="btn">取消</button>
    </div>
</form>