<?php
//后台自动生成，请毋修改by mashanling
//最后更新时间:2012-12-21 12:49:59

return array (
  0 => 
  array (
    'area_id' => '1',
    'area_name' => '中国',
    'parent_id' => '0',
    'area_code' => '',
    'is_show' => '1',
    'sort_order' => '0',
    'level' => '1',
    'node' => '1',
    'leaf' => false,
    'expanded' => true,
    'checked' => false,
    'data' => 
    array (
      0 => 
      array (
        'area_id' => '2',
        'area_name' => '北京',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,2',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      1 => 
      array (
        'area_id' => '3',
        'area_name' => '安徽',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,3',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      2 => 
      array (
        'area_id' => '4',
        'area_name' => '福建',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,4',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      3 => 
      array (
        'area_id' => '5',
        'area_name' => '甘肃',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,5',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      4 => 
      array (
        'area_id' => '6',
        'area_name' => '广东',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,6',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      5 => 
      array (
        'area_id' => '7',
        'area_name' => '广西',
        'parent_id' => '1',
        'area_code' => 'guangxi',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,7',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      6 => 
      array (
        'area_id' => '8',
        'area_name' => '贵州',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,8',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      7 => 
      array (
        'area_id' => '9',
        'area_name' => '海南',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,9',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      8 => 
      array (
        'area_id' => '10',
        'area_name' => '河北',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,10',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      9 => 
      array (
        'area_id' => '11',
        'area_name' => '河南',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,11',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      10 => 
      array (
        'area_id' => '12',
        'area_name' => '黑龙江',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,12',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      11 => 
      array (
        'area_id' => '13',
        'area_name' => '湖北',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,13',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      12 => 
      array (
        'area_id' => '14',
        'area_name' => '湖南',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,14',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      13 => 
      array (
        'area_id' => '15',
        'area_name' => '吉林',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,15',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      14 => 
      array (
        'area_id' => '16',
        'area_name' => '江苏',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,16',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      15 => 
      array (
        'area_id' => '17',
        'area_name' => '江西',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,17',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      16 => 
      array (
        'area_id' => '18',
        'area_name' => '辽宁',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,18',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      17 => 
      array (
        'area_id' => '19',
        'area_name' => '内蒙古',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,19',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      18 => 
      array (
        'area_id' => '20',
        'area_name' => '宁夏',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,20',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      19 => 
      array (
        'area_id' => '21',
        'area_name' => '青海',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,21',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      20 => 
      array (
        'area_id' => '22',
        'area_name' => '山东',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,22',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      21 => 
      array (
        'area_id' => '23',
        'area_name' => '山西',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,23',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      22 => 
      array (
        'area_id' => '24',
        'area_name' => '陕西',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,24',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      23 => 
      array (
        'area_id' => '25',
        'area_name' => '上海',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,25',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      24 => 
      array (
        'area_id' => '26',
        'area_name' => '四川',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,26',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      25 => 
      array (
        'area_id' => '27',
        'area_name' => '天津',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,27',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      26 => 
      array (
        'area_id' => '28',
        'area_name' => '西藏',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,28',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      27 => 
      array (
        'area_id' => '29',
        'area_name' => '新疆',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,29',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      28 => 
      array (
        'area_id' => '30',
        'area_name' => '云南',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,30',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      29 => 
      array (
        'area_id' => '31',
        'area_name' => '浙江',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,31',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      30 => 
      array (
        'area_id' => '32',
        'area_name' => '重庆',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,32',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      31 => 
      array (
        'area_id' => '33',
        'area_name' => '香港',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,33',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      32 => 
      array (
        'area_id' => '34',
        'area_name' => '澳门',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,34',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      33 => 
      array (
        'area_id' => '35',
        'area_name' => '台湾',
        'parent_id' => '1',
        'area_code' => '',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,35',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      34 => 
      array (
        'area_id' => '3416',
        'area_name' => 'f',
        'parent_id' => '1',
        'area_code' => 'f',
        'is_show' => '1',
        'sort_order' => '0',
        'level' => '2',
        'node' => '1,3416',
        'leaf' => false,
        'expanded' => false,
        'checked' => false,
      ),
      35 => 
      array (
        'area_id' => '3424',
        'area_name' => 'd',
        'parent_id' => '1',
        'area_code' => 'd',
        'is_show' => '1',
        'sort_order' => '3424',
        'level' => '2',
        'node' => '1,3424',
        'leaf' => true,
        'expanded' => false,
        'checked' => false,
      ),
    ),
  ),
  1 => 
  array (
    'area_id' => '3425',
    'area_name' => 'mr',
    'parent_id' => '0',
    'area_code' => '',
    'is_show' => '0',
    'sort_order' => '0',
    'level' => '1',
    'node' => '3425',
    'leaf' => true,
    'expanded' => true,
    'checked' => false,
  ),
);