<?php
//后台自动生成，请毋修改
//最后更新时间:2013-06-25 18:00:39

return array (
  0 => 
  array (
    'module_id' => '1',
    'parent_id' => '0',
    'module_name' => '整站',
    'sort_order' => '1',
    'level' => '1',
    'node' => '1',
    'memo' => '',
    'leaf' => true,
    'checked' => false,
  ),
  1 => 
  array (
    'module_id' => '2',
    'parent_id' => '0',
    'module_name' => '前台',
    'sort_order' => '2',
    'level' => '1',
    'node' => '2',
    'memo' => '',
    'leaf' => false,
    'checked' => false,
    'data' => 
    array (
      0 => 
      array (
        'module_id' => '5',
        'parent_id' => '2',
        'module_name' => 'common',
        'sort_order' => '5',
        'level' => '2',
        'node' => '2,5',
        'memo' => '前台通用语言包',
        'leaf' => true,
        'checked' => false,
      ),
      1 => 
      array (
        'module_id' => '24',
        'parent_id' => '2',
        'module_name' => 'blog',
        'sort_order' => '24',
        'level' => '2',
        'node' => '2,24',
        'memo' => '博客',
        'leaf' => true,
        'checked' => false,
      ),
      2 => 
      array (
        'module_id' => '25',
        'parent_id' => '2',
        'module_name' => 'comments',
        'sort_order' => '25',
        'level' => '2',
        'node' => '2,25',
        'memo' => '留言评论',
        'leaf' => true,
        'checked' => false,
      ),
      3 => 
      array (
        'module_id' => '26',
        'parent_id' => '2',
        'module_name' => 'guestbook',
        'sort_order' => '26',
        'level' => '2',
        'node' => '2,26',
        'memo' => '留言',
        'leaf' => true,
        'checked' => false,
      ),
    ),
  ),
  2 => 
  array (
    'module_id' => '3',
    'parent_id' => '0',
    'module_name' => '后台',
    'sort_order' => '3',
    'level' => '1',
    'node' => '3',
    'memo' => '',
    'leaf' => false,
    'checked' => false,
    'data' => 
    array (
      0 => 
      array (
        'module_id' => '6',
        'parent_id' => '3',
        'module_name' => 'common',
        'sort_order' => '6',
        'level' => '2',
        'node' => '3,6',
        'memo' => '后台通用语言包',
        'leaf' => true,
        'checked' => false,
      ),
      1 => 
      array (
        'module_id' => '7',
        'parent_id' => '3',
        'module_name' => 'admin',
        'sort_order' => '7',
        'level' => '2',
        'node' => '3,7',
        'memo' => '管理员模块',
        'leaf' => true,
        'checked' => false,
      ),
      2 => 
      array (
        'module_id' => '8',
        'parent_id' => '3',
        'module_name' => 'adminloginhistory',
        'sort_order' => '8',
        'level' => '2',
        'node' => '3,8',
        'memo' => '管理员登陆历史',
        'leaf' => true,
        'checked' => false,
      ),
      3 => 
      array (
        'module_id' => '9',
        'parent_id' => '3',
        'module_name' => 'area',
        'sort_order' => '9',
        'level' => '2',
        'node' => '3,9',
        'memo' => '国家地区',
        'leaf' => true,
        'checked' => false,
      ),
      4 => 
      array (
        'module_id' => '10',
        'parent_id' => '3',
        'module_name' => 'blog',
        'sort_order' => '10',
        'level' => '2',
        'node' => '3,10',
        'memo' => '博客',
        'leaf' => true,
        'checked' => false,
      ),
      5 => 
      array (
        'module_id' => '11',
        'parent_id' => '3',
        'module_name' => 'category',
        'sort_order' => '11',
        'level' => '2',
        'node' => '3,11',
        'memo' => '博客分类',
        'leaf' => true,
        'checked' => false,
      ),
      6 => 
      array (
        'module_id' => '12',
        'parent_id' => '3',
        'module_name' => 'comments',
        'sort_order' => '12',
        'level' => '2',
        'node' => '3,12',
        'memo' => '留言评论',
        'leaf' => true,
        'checked' => false,
      ),
      7 => 
      array (
        'module_id' => '13',
        'parent_id' => '3',
        'module_name' => 'field',
        'sort_order' => '13',
        'level' => '2',
        'node' => '3,13',
        'memo' => '表单域',
        'leaf' => true,
        'checked' => false,
      ),
      8 => 
      array (
        'module_id' => '14',
        'parent_id' => '3',
        'module_name' => 'html',
        'sort_order' => '14',
        'level' => '2',
        'node' => '3,14',
        'memo' => '生成静态页管理',
        'leaf' => true,
        'checked' => false,
      ),
      9 => 
      array (
        'module_id' => '15',
        'parent_id' => '3',
        'module_name' => 'languageitems',
        'sort_order' => '15',
        'level' => '2',
        'node' => '3,15',
        'memo' => '语言项',
        'leaf' => true,
        'checked' => false,
      ),
      10 => 
      array (
        'module_id' => '16',
        'parent_id' => '3',
        'module_name' => 'languagemodules',
        'sort_order' => '16',
        'level' => '2',
        'node' => '3,16',
        'memo' => '语言包模块',
        'leaf' => true,
        'checked' => false,
      ),
      11 => 
      array (
        'module_id' => '17',
        'parent_id' => '3',
        'module_name' => 'log',
        'sort_order' => '17',
        'level' => '2',
        'node' => '3,17',
        'memo' => '系统日志',
        'leaf' => true,
        'checked' => false,
      ),
      12 => 
      array (
        'module_id' => '18',
        'parent_id' => '3',
        'module_name' => 'login',
        'sort_order' => '18',
        'level' => '2',
        'node' => '3,18',
        'memo' => '后台登陆',
        'leaf' => true,
        'checked' => false,
      ),
      13 => 
      array (
        'module_id' => '19',
        'parent_id' => '3',
        'module_name' => 'mail',
        'sort_order' => '19',
        'level' => '2',
        'node' => '3,19',
        'memo' => '邮件模板',
        'leaf' => true,
        'checked' => false,
      ),
      14 => 
      array (
        'module_id' => '20',
        'parent_id' => '3',
        'module_name' => 'mailhistory',
        'sort_order' => '20',
        'level' => '2',
        'node' => '3,20',
        'memo' => '邮件历史',
        'leaf' => true,
        'checked' => false,
      ),
      15 => 
      array (
        'module_id' => '21',
        'parent_id' => '3',
        'module_name' => 'menu',
        'sort_order' => '21',
        'level' => '2',
        'node' => '3,21',
        'memo' => '后台菜单',
        'leaf' => true,
        'checked' => false,
      ),
      16 => 
      array (
        'module_id' => '22',
        'parent_id' => '3',
        'module_name' => 'miniblog',
        'sort_order' => '22',
        'level' => '2',
        'node' => '3,22',
        'memo' => '微博',
        'leaf' => true,
        'checked' => false,
      ),
      17 => 
      array (
        'module_id' => '23',
        'parent_id' => '3',
        'module_name' => 'role',
        'sort_order' => '23',
        'level' => '2',
        'node' => '3,23',
        'memo' => '管理员角色',
        'leaf' => true,
        'checked' => false,
      ),
    ),
  ),
);